// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCars.Data;

namespace RentCars.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201225130606_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RentCars.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("RentCars.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("RentCars.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GearType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LocationId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 921, DateTimeKind.Utc).AddTicks(6582),
                            Description = "The 2020 Mazda 6 doesn’t make a bad step. This year, the mid-size sedan returns mostly unchanged from last year’s version, albeit with standard safety hardware that was optional last year.",
                            GearType = 2,
                            Image = "https://www.mazdausa.com/siteassets/vehicles/2020/mazda6/trims/gt/2020-mazda6-gt-soul-red-crystal.png",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 1,
                            Model = "Mazda 6",
                            PricePerDay = 60m,
                            Speed = 180,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(25),
                            Description = "The Mazda 3 is a family hatch, not an SUV or a crossover or pretending to be something it’s not. These days you don’t go to the expense of creating a whole new platform from the ground up without doing more than one thing with it, though, so expect more to come from the 3’s box of bits.",
                            GearType = 1,
                            Image = "https://www.pngitem.com/pimgs/m/610-6106111_2020-mazda-3-black-hd-png-download.png",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 1,
                            Model = "Mazda 3",
                            PricePerDay = 39m,
                            Speed = 180,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(935),
                            Description = "The X7 by contrast is about luxury. It takes themes from the facelifted 7 Series and the 8er, to make BMW’s three-flagship fleet. They want us to see this top-end trio as a separate high-end luxury series.",
                            GearType = 2,
                            Image = "https://images.hgmsites.net/hug/2020-bmw-x7_100728938_h.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 1,
                            Model = "BMW X7",
                            PricePerDay = 80m,
                            Speed = 155,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(1120),
                            Description = "The big Tesla. The one that seats seven and has every other firm on the planet that builds premium SUVs in a bit of a panic. Underneath, the architecture is similar to the Model S (massive battery pack, electric motors, aluminium chassis), but all Model X are four-wheel drive, so have twin electric motors, one driving each axle. ",
                            GearType = 2,
                            Image = "https://www.autocar.co.uk/sites/autocar.co.uk/files/images/car-reviews/first-drives/legacy/1-tesla-model-x-long-range-2019-uk-fd-hero-front.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 1,
                            Model = "Tesla Model X",
                            PricePerDay = 80m,
                            Speed = 245,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(1283),
                            Description = "Developed by Mazda, launched by Scion, and now marketed as a Toyota, the Yaris iA proves that subcompact cars can delight. A different model from the Toyota Yaris hatchback, the frisky iA sedan stands out in a segment filled with insubstantial models. It feels refined for this entry-level class, with a smooth and willing four-cylinder engine, slick six-speed automatic transmission, and relatively compliant ride.",
                            GearType = 2,
                            Image = "https://media.ed.edmunds-media.com/toyota/yaris/2019/oem/2019_toyota_yaris_sedan_xle_fq_oem_1_1600.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 1,
                            Model = "Toyota Yaris iA",
                            PricePerDay = 40m,
                            Speed = 180,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(1464),
                            Description = "The Optima is a vehicle that delivers all of these virtues in a stylish, value-laden package that’s filled with features usually found on pricier cars. With outstanding reliability and extensive warranty coverage, savvy sedan shoppers should take this recently redesigned car for a test drive.",
                            GearType = 2,
                            Image = "https://i.dir-i.net/CMS/2019/12/28/k/5f_kzmt31.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 2,
                            Model = "Kia Optima",
                            PricePerDay = 36m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(1629),
                            Description = "The Subaru Forester sets the standard for small SUVs, combining relatively roomy packaging, fuel efficiency, solid reliability, and easy access. Large windows and a boxy shape maximize room for passengers and gear in sharp contrast to style trends exhibited by competitors that compromise practicality. ",
                            GearType = 1,
                            Image = "https://cars.usnews.com/static/images/Auto/custom/14103/2020_Subaru_Forester_2.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 3,
                            Model = "Subaru Forester",
                            PricePerDay = 55m,
                            Speed = 230,
                            Year = 2020
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(1788),
                            Description = "The 2020 Honda Ridgeline, the second generation of Honda's innovative, one-of-a-kind pickup truck with innovations such as the In-Bed Trunk and world's first Truck Bed Audio System was chosen by a panel of expert automotive journalists as the 2020 North America Truck of the Year. ",
                            GearType = 1,
                            Image = "https://blogmedia.dealerfire.com/wp-content/uploads/sites/1074/2019/12/2020-Honda-Ridgeline-exterior-side-shot-with-Obsidian-Blue-Pearl-paint-color-parked-on-a-beach-line-of-gravel-and-sand-next-to-the-ocean_o.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 4,
                            Model = "Honda RidgeLine",
                            PricePerDay = 20m,
                            Speed = 220,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(1949),
                            Description = "The Insignia was the flagship of the Opel range and offered as a medium-large sedan and station wagon. Passenger space is good, with almost as much legroom, but slightly less width in the back seat than Commodore and Falcon.",
                            GearType = 1,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq_MfOl8X2QtiGoqH9SOVrrml25pw6g3Rk5w&usqp=CAU",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 5,
                            Model = "Opel Insignia",
                            PricePerDay = 15m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(2119),
                            Description = "The Impala continues to reign as the leading large sedan. Slide behind the wheel and you can see why. Roomy, supportive seats put you in the perfect position to access the intuitive controls. Despite its prodigious size, the Impala’s handling is responsive and secure.",
                            GearType = 2,
                            Image = "https://banner2.cleanpng.com/20180410/xrw/kisspng-2017-chevrolet-impala-2018-chevrolet-impala-chevro-chevrolet-5accd70885ac83.6020416415233738325475.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 6,
                            Model = "Chevrolet Impala",
                            PricePerDay = 12m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 923, DateTimeKind.Utc).AddTicks(2282),
                            Description = "No matter which new hybrid SUV model you choose, you’ll enjoy distinct styling, flexible design, and impressive fuel economy. Full-size Toyota SUV hybrids deliver roomy versatility, ample seating capacity and cargo space, easy-to-read controls, and countless thoughtful amenities for your active and growing family. For a new hybrid SUV with even more maneuverability, check out a versatile Toyota hybrid crossover SUV instead. In addition to ample cargo space, expect competitive fuel efficiency and Toyota quality in every hybrid SUV we offer. Help blaze your trail with less fuel and more fun. Find the best hybrid SUV for your next adventure.",
                            GearType = 2,
                            Image = "https://media.ed.edmunds-media.com/toyota/rav4-hybrid/2019/oem/2019_toyota_rav4-hybrid_4dr-suv_limited_fq_oem_7_815.jpg",
                            InUse = true,
                            IsDeleted = false,
                            LocationId = 7,
                            Model = "TOYOTA RAV4 Hybrid",
                            PricePerDay = 39m,
                            Speed = 280,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("RentCars.Data.Models.CarRentDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("CarRentDays");
                });

            modelBuilder.Entity("RentCars.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 916, DateTimeKind.Utc).AddTicks(2588),
                            IsDeleted = false,
                            Name = "Sofia, Airport Terminal 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(1906),
                            IsDeleted = false,
                            Name = "Sofia, Airport Terminal 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(2347),
                            IsDeleted = false,
                            Name = "Plovdiv, Novotel"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(2488),
                            IsDeleted = false,
                            Name = "Stara Zagora, Stadium Beroe"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(2625),
                            IsDeleted = false,
                            Name = "Shumen, Post Office"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(2778),
                            IsDeleted = false,
                            Name = "Burgas, Post Office"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(2907),
                            IsDeleted = false,
                            Name = "Varna, Dolphinarium"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(3034),
                            IsDeleted = false,
                            Name = "Pleven, Hotel Bulgaria"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(3162),
                            IsDeleted = false,
                            Name = "Sozopol, Old City Post Office"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 12, 25, 13, 6, 4, 920, DateTimeKind.Utc).AddTicks(3474),
                            IsDeleted = false,
                            Name = "Lovech, Varosha Gallery"
                        });
                });

            modelBuilder.Entity("RentCars.Data.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickUpLocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RentEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CarId");

                    b.HasIndex("PickUpLocationId");

                    b.HasIndex("ReturnLocationId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RentCars.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CarId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RentCars.Data.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCars.Data.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RentCars.Data.Models.Car", b =>
                {
                    b.HasOne("RentCars.Data.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RentCars.Data.Models.CarRentDays", b =>
                {
                    b.HasOne("RentCars.Data.Models.Car", "Car")
                        .WithMany("RentDays")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RentCars.Data.Models.Order", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCars.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCars.Data.Models.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCars.Data.Models.Location", "ReturnLocation")
                        .WithMany()
                        .HasForeignKey("ReturnLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCars.Data.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");
                });

            modelBuilder.Entity("RentCars.Data.Models.Review", b =>
                {
                    b.HasOne("RentCars.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentCars.Data.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
